### ISSUE TITLE
Как этим пользоваться?

### ISSUE THREAD

**Issue by olekhov** [stillru/astralinux-packer-template#24]
Степан, добрый день.

Можете дать более развёрнутые пояснения, как этим пользоваться?

Мне нужно решить схожую задачу - создать несколько систем из Астры 1.6 (смоленск), с апдейтами и без, с инструментами разработчика и без, с ЗПС и без оной, в разных вариантах. 
И тестировать сборку (и работу) third-party софта на этих машинах.

Пока что всё это делается вручную и муторно. Есть стойкое желание это автоматизировать и внятно задокументировать.
Начал смотреть в сторону vagrant, нашёл вашу репу.

Очень интересно и ничего не понятно :)

**Comment by olekhov** [comment]
Разобрался, как запустить сборку, что-то пошло.
Переделал на virtualbox, так надо.

Пытаюсь адаптировать для сборки Смоленска 1.6
Столкнулся с проблемой. У вас инсталляция идёт с netinst. Оно подразумевает доступность репозитория в интернете.
Смоленск - специального назначения, у них урл репозитория - какой-то внутренний адрес РусБиТеха.

Значит, источник пакетов - на DVD. Если запускать стандартный инсталлятор, то он не поднимает сеть и не получает preseed. 
Есть идеи, как обойтись без ремастеринга iso ?

**Comment by stillru** [comment]
@olekhov спасибо за проявленный интерес. Увы - у меня нет под рукой смоленска. 

Вообще packer запускает собственный http и оттуда тянет preseed. Надо копать в сторону способов подмонтирования источника preseed файлов.

**Comment by stillru** [comment]
Вчера не разобрался с ходу в чём проблема.

Обходное решение - добавить в установщик свой собственный репозиторий с пакетами. Тогда на моменте выкачивания пакетов он будет обращаться к нему, а не к вшитому разработчиками астры.

``` {shell}
    preseed apt-setup/local0/comment string My repository
    preseed apt-setup/local0/repository string http://www.example.org/packages/${distro} ${suite} main
    preseed apt-setup/local0/source boolean true
    preseed apt-setup/local0/key string http://www.example.org/packages/public.gpg
```

**Comment by stillru** [comment]
Закрываю обращение. К сожалению решения не опубликовано.
